import type { Doc } from "../types";

// Guide documents (31 docs organized by display categories)
export const docs: Doc[] = [
  {
    slug: "getting-started",
    titleZh: "atypica.AI 用户研究旅程",
    titleEn: "atypica.AI User Research Journey",
    category: "guide",
    descriptionZh: "通过气泡咖啡案例，完整展示用户如何使用 atypica.AI 完成商业研究的全过程",
    descriptionEn:
      "Complete demonstration of how users conduct business research with atypica.AI through a real-world scenario",
    filePathZh: "docs/product/guides/overview/getting-started.zh.md",
    filePathEn: "docs/product/guides/overview/getting-started.en.md",
    directory: "general",
  },
  // plan-mode (6)
  {
    slug: "first-time-getting-started",
    titleZh: "第一次使用atypica，应该从哪里开始？",
    titleEn: "First time using atypica, where should I start?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/first-time-getting-started.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/first-time-getting-started.en.md",
    directory: "plan-mode",
  },
  {
    slug: "create-research-project",
    titleZh: "如何创建我的第一个研究项目？",
    titleEn: "How to create my first research project?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/create-research-project.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/create-research-project.en.md",
    directory: "plan-mode",
  },
  {
    slug: "writing-brief",
    titleZh: "brief写得简单和详细，对结果影响大吗？如何写出好的brief？有模板吗？",
    titleEn:
      "Does brief length (simple vs detailed) affect results significantly? How to write good briefs? Are there templates?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/writing-brief.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/writing-brief.en.md",
    directory: "plan-mode",
  },
  {
    slug: "interpreting-research-reports",
    titleZh: "如何解读AI Research生成的报告？哪些部分最重要？",
    titleEn: "How to interpret AI Research-generated reports? Which parts are most important?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/interpreting-research-reports.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/interpreting-research-reports.en.md",
    directory: "plan-mode",
  },
  {
    slug: "report-data-visualization",
    titleZh:
      "生成的访谈报告可以看到相关的数据可视化的结果吗？例如：性别占比，年龄占比，对某个平台的使用频率占比等",
    titleEn:
      "Can generated interview reports show data visualization results? For example: gender ratio, age distribution, platform usage frequency distribution, etc.",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/report-data-visualization.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/report-data-visualization.en.md",
    directory: "plan-mode",
  },
  {
    slug: "export-and-share",
    titleZh: "怎么导出和分享我的研究结果？",
    titleEn: "How to export and share my research results?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/plan-mode/export-and-share.zh.md",
    filePathEn: "docs/product/user-guide/plan-mode/export-and-share.en.md",
    directory: "plan-mode",
  },
  // scout-agent (2)
  {
    slug: "social-media-scanning",
    titleZh: "如何让你们帮我观察社交媒体上的目标用户？",
    titleEn: "How to Have You Scan Social Media for Target Users?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/scout-agent/social-media-scanning.zh.md",
    filePathEn: "docs/product/user-guide/scout-agent/social-media-scanning.en.md",
    directory: "scout-agent",
  },
  {
    slug: "data-source-platforms",
    titleZh: "AI研究获取的数据来源是哪些平台的？",
    titleEn: "What Platforms Are the Data Sources for AI Research?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/scout-agent/data-source-platforms.zh.md",
    filePathEn: "docs/product/user-guide/scout-agent/data-source-platforms.en.md",
    directory: "scout-agent",
  },
  // memory-system (1)
  {
    slug: "how-to-configure-memory",
    titleZh: "如何设置让AI记住我的研究需求？",
    titleEn: "How to Configure AI to Remember My Research Needs?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/memory-system/how-to-configure-memory.zh.md",
    filePathEn: "docs/product/user-guide/memory-system/how-to-configure-memory.en.md",
    directory: "memory-system",
  },
  // ai-persona (6)
  {
    slug: "search-public-persona-library",
    titleZh:
      "AI访谈创建的项目后怎么在公众人设库里选择最合适的AI人设？公众人设库应该输入什么标签来查找？",
    titleEn:
      "After Creating an Interview Project, How to Search and Select the Most Suitable AI Personas from the Public Persona Library? What Keywords Should I Use?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/search-public-persona-library.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/search-public-persona-library.en.md",
    directory: "ai-persona",
  },
  {
    slug: "tier-differences",
    titleZh: "怎么选择合适的AI人设？",
    titleEn: "How to Choose the Right AI Persona?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/tier-differences.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/tier-differences.en.md",
    directory: "ai-persona",
  },
  {
    slug: "create-your-own-persona",
    titleZh: "怎么创建我自己的AI人设？",
    titleEn: "How to Create My Own AI Persona?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/create-your-own-persona.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/create-your-own-persona.en.md",
    directory: "ai-persona",
  },
  {
    slug: "upload-interview-transcripts",
    titleZh: "如何上传访谈记录创建AI Persona？支持哪些格式？如何导入我已有的用户数据？",
    titleEn:
      "How to Upload Interview Transcripts to Create AI Persona? What Formats Are Supported? How to Import My Existing User Data?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/upload-interview-transcripts.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/upload-interview-transcripts.en.md",
    directory: "ai-persona",
  },
  {
    slug: "batch-create-personas",
    titleZh: "可以支持上传多个用户的访谈数据，创建多个AI人设吗？",
    titleEn: "Can I Upload Multiple Users' Interview Data to Create Multiple AI Personas?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/batch-create-personas.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/batch-create-personas.en.md",
    directory: "ai-persona",
  },
  {
    slug: "manage-persona-library",
    titleZh: "怎么管理和整理我的人设库？",
    titleEn: "How to Manage and Organize My Persona Library?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/ai-persona/manage-persona-library.zh.md",
    filePathEn: "docs/product/user-guide/ai-persona/manage-persona-library.en.md",
    directory: "ai-persona",
  },
  // interview-discussion (6)
  {
    slug: "how-to-start-interview",
    titleZh: "如何开始一次访谈？",
    titleEn: "How to Start an Interview?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/interview-discussion/how-to-start-interview.zh.md",
    filePathEn: "docs/product/user-guide/interview-discussion/how-to-start-interview.en.md",
    directory: "interview-discussion",
  },
  {
    slug: "interview-persona-count",
    titleZh: "一次AI Interview最多可以选择多少个Persona？",
    titleEn: "How Many Personas Can I Select for One AI Interview?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/interview-discussion/interview-persona-count.zh.md",
    filePathEn: "docs/product/user-guide/interview-discussion/interview-persona-count.en.md",
    directory: "interview-discussion",
  },
  {
    slug: "persona-chat-settings",
    titleZh: "不同Persona之间可以对话吗？如何设置？",
    titleEn: "Can Personas Talk to Each Other? How to Set It Up?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/interview-discussion/persona-chat-settings.zh.md",
    filePathEn: "docs/product/user-guide/interview-discussion/persona-chat-settings.en.md",
    directory: "interview-discussion",
  },
  {
    slug: "multi-persona-discussion-settings",
    titleZh: "如何让多个AI人设一起讨论？",
    titleEn: "How to Have Multiple AI Personas Discuss Together?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh:
      "docs/product/user-guide/interview-discussion/multi-persona-discussion-settings.zh.md",
    filePathEn:
      "docs/product/user-guide/interview-discussion/multi-persona-discussion-settings.en.md",
    directory: "interview-discussion",
  },
  {
    slug: "interview-vs-research-choice",
    titleZh: "AI Interview和AI Research什么时候用哪个？",
    titleEn: "When to Use AI Interview vs AI Research?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/interview-discussion/interview-vs-research-choice.zh.md",
    filePathEn: "docs/product/user-guide/interview-discussion/interview-vs-research-choice.en.md",
    directory: "interview-discussion",
  },
  {
    slug: "interview-report-content",
    titleZh: "访谈报告里有什么内容？在哪里查看？",
    titleEn: "What's in the Interview Report? Where to View It?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/interview-discussion/interview-report-content.zh.md",
    filePathEn: "docs/product/user-guide/interview-discussion/interview-report-content.en.md",
    directory: "interview-discussion",
  },
  // sage-system (2)
  {
    slug: "using-ai-expert-interviews",
    titleZh: "怎么用AI专家智能体来访谈AI角色？",
    titleEn: "How to Use AI Expert Agent to Interview AI Personas?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/sage-system/using-ai-expert-interviews.zh.md",
    filePathEn: "docs/product/user-guide/sage-system/using-ai-expert-interviews.en.md",
    directory: "sage-system",
  },
  {
    slug: "sage-vs-chatgpt-difference",
    titleZh: "AI专家智能体和直接给chatgpt定义人设再询问有什么区别？",
    titleEn:
      "What's the Difference Between AI Expert Agent and Directly Defining Personas in ChatGPT?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/sage-system/sage-vs-chatgpt-difference.zh.md",
    filePathEn: "docs/product/user-guide/sage-system/sage-vs-chatgpt-difference.en.md",
    directory: "sage-system",
  },
  // general (7)
  {
    slug: "free-vs-paid-versions",
    titleZh: "免费版和付费版有什么区别？",
    titleEn: "What's the Difference Between Free and Paid Versions?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/free-vs-paid-versions.zh.md",
    filePathEn: "docs/product/user-guide/general/free-vs-paid-versions.en.md",
    directory: "general",
  },
  {
    slug: "usage-records-billing",
    titleZh: "如何查看我的使用记录和账单？",
    titleEn: "How to View My Usage Records and Billing?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/usage-records-billing.zh.md",
    filePathEn: "docs/product/user-guide/general/usage-records-billing.en.md",
    directory: "general",
  },
  {
    slug: "invite-colleagues",
    titleZh: "如何邀请同事一起使用？",
    titleEn: "How to Invite Colleagues to Use Together?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/invite-colleagues.zh.md",
    filePathEn: "docs/product/user-guide/general/invite-colleagues.en.md",
    directory: "general",
  },
  {
    slug: "team-sharing-settings",
    titleZh: "如何和团队共享人设库和研究项目？",
    titleEn: "How to Share Persona Library and Research Projects with Team?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/team-sharing-settings.zh.md",
    filePathEn: "docs/product/user-guide/general/team-sharing-settings.en.md",
    directory: "general",
  },
  {
    slug: "data-privacy-security",
    titleZh: "我上传的访谈数据会泄露吗？Atypica会不会用我的数据做什么？",
    titleEn: "Will My Uploaded Interview Data Be Leaked? Will Atypica Use My Data for Anything?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/data-privacy-security.zh.md",
    filePathEn: "docs/product/user-guide/general/data-privacy-security.en.md",
    directory: "general",
  },
  {
    slug: "editing-reports",
    titleZh: "生成的报告支持二次编辑吗？",
    titleEn: "Can Generated Reports Be Edited?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/editing-reports.zh.md",
    filePathEn: "docs/product/user-guide/general/editing-reports.en.md",
    directory: "general",
  },
  {
    slug: "exit-during-research",
    titleZh: "假如我在正在研究时退出，研究会不会终止？",
    titleEn: "If I exit during research, will it terminate?",
    category: "guide",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/user-guide/general/exit-during-research.zh.md",
    filePathEn: "docs/product/user-guide/general/exit-during-research.en.md",
    directory: "general",
  },
];
