import type { Doc } from "../types";

// FAQ documents (19 docs organized by display categories)
export const docs: Doc[] = [
  // plan-mode (2)
  {
    slug: "comparison-with-gemini-deepresearch",
    titleZh:
      "AI research和Gemini的deep research有什么区别？和市面上的deep research生成的商业报告有什么区别？",
    titleEn:
      "What's the difference between AI research and Gemini's deep research? What's the difference from business reports generated by deep research on the market?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/research/comparison-with-gemini-deepresearch.zh.md",
    filePathEn: "docs/product/faq/research/comparison-with-gemini-deepresearch.en.md",
  },
  {
    slug: "research-framework-model",
    titleZh:
      "AI研究报告采用的是什么研究框架来分析？例如真实的市场分析中有SWOT、PEST各种分析模型，这个分析路径是AI自定义的吗？",
    titleEn:
      "What research framework does AI research reports use for analysis? For example, real market analysis has SWOT, PEST, and various analytical models. Is this analysis path AI-customized?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/research/research-framework-model.zh.md",
    filePathEn: "docs/product/faq/research/research-framework-model.en.md",
  },
  // scout-agent (1)
  {
    slug: "how-social-scanning-helps",
    titleZh:
      "你们的这个社媒观察能力，能怎么帮助我？比如你们介绍里的「帮助新市场接触不到直接目标用户的场景」，具体是指什么情况？",
    titleEn:
      'Your social media observation capability, how can it help me? For example, the "helping with scenarios where you cannot directly reach target users in new markets" mentioned in your introduction, what specific situations does this refer to?',
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/research/how-social-scanning-helps.zh.md",
    filePathEn: "docs/product/faq/research/how-social-scanning-helps.en.md",
  },
  // memory-system (1)
  {
    slug: "competitor-homogenization-issue",
    titleZh: "我的竞争对手也在用你们的产品，会不会大家都得到一样的结论？",
    titleEn: "If my competitors also use your product, won't we all reach the same conclusions?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/research/competitor-homogenization-issue.zh.md",
    filePathEn: "docs/product/faq/research/competitor-homogenization-issue.en.md",
  },
  // ai-persona (9)
  {
    slug: "how-300k-personas-built",
    titleZh: "你们的30万AI人设是怎么做出来的？一个个手工写的吗？",
    titleEn: "How are your 300K AI Personas built? Written manually one by one?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/how-300k-personas-built.zh.md",
    filePathEn: "docs/product/faq/persona/how-300k-personas-built.en.md",
  },
  {
    slug: "are-personas-too-similar",
    titleZh: "30万AI人设，会不会其实都差不多？",
    titleEn: "With 300K AI Personas, aren't they all too similar?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/are-personas-too-similar.zh.md",
    filePathEn: "docs/product/faq/persona/are-personas-too-similar.en.md",
  },
  {
    slug: "cost-comparison",
    titleZh: "AI人设的成本真的比真人低吗？",
    titleEn: "Are AI Persona costs really lower than real humans?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/cost-comparison.zh.md",
    filePathEn: "docs/product/faq/persona/cost-comparison.en.md",
  },
  {
    slug: "difference-from-chatgpt",
    titleZh: "你们的AI人设和我自己用ChatGPT创建角色有什么区别？",
    titleEn:
      "What's the difference between your AI Personas and creating characters myself with ChatGPT?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/difference-from-chatgpt.zh.md",
    filePathEn: "docs/product/faq/persona/difference-from-chatgpt.en.md",
  },
  {
    slug: "gap-from-real-people",
    titleZh: "你们的AI人设和真人的差距到底有多大？",
    titleEn: "What's the gap between your AI Personas and real humans?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/gap-from-real-people.zh.md",
    filePathEn: "docs/product/faq/persona/gap-from-real-people.en.md",
  },
  {
    slug: "niche-traditional-industries",
    titleZh: "如果我做的是小众/传统行业，AI人设库里有相关的人吗？",
    titleEn:
      "If I work in a niche/traditional industry, are there relevant personas in the AI Persona library?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/niche-traditional-industries.zh.md",
    filePathEn: "docs/product/faq/persona/niche-traditional-industries.en.md",
  },
  {
    slug: "only-correct-answers",
    titleZh: "AI人设的回答会不会只给'正确答案'？",
    titleEn: "Will AI Persona responses only give 'correct answers'?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/only-correct-answers.zh.md",
    filePathEn: "docs/product/faq/persona/only-correct-answers.en.md",
  },
  {
    slug: "reusability-guarantee",
    titleZh: "你们说这个AI角色是可复用的资源，怎么保证我的这个AI人设可以回答我不同领域的问题呢？",
    titleEn:
      "You say this AI character is a reusable resource, how do you guarantee my AI Persona can answer my questions in different domains?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/reusability-guarantee.zh.md",
    filePathEn: "docs/product/faq/persona/reusability-guarantee.en.md",
  },
  {
    slug: "why-not-use-real-people",
    titleZh: "为什么不直接找真人做研究，要用AI？",
    titleEn: "Why not just use real people for research instead of AI?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/persona/why-not-use-real-people.zh.md",
    filePathEn: "docs/product/faq/persona/why-not-use-real-people.en.md",
  },
  // interview-discussion (4)
  {
    slug: "ai-interview-vs-survey",
    titleZh:
      "AI访谈是基于我设定好的问题自动发散还是就原有这些问题来回答，和发放问卷给受访者填写有什么区别？",
    titleEn:
      "Is AI interview based on my pre-set questions for automatic divergence, or just answering these questions? What's the difference from sending out surveys to respondents?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/interview/ai-interview-vs-survey.zh.md",
    filePathEn: "docs/product/faq/interview/ai-interview-vs-survey.en.md",
  },
  {
    slug: "ai-use-case-advantages",
    titleZh: "有什么使用场景，AI人设的使用真比真人好吗？",
    titleEn: "In what scenarios is using AI personas truly better than real people?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/interview/ai-use-case-advantages.zh.md",
    filePathEn: "docs/product/faq/interview/ai-use-case-advantages.en.md",
  },
  {
    slug: "competitor-homogenization",
    titleZh: "我的竞争对手也在用你们的产品，会不会大家都得到一样的结论？",
    titleEn:
      "My competitors are also using your product, will everyone reach the same conclusions?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/interview/competitor-homogenization.zh.md",
    filePathEn: "docs/product/faq/interview/competitor-homogenization.en.md",
  },
  {
    slug: "when-use-ai-not-real-people",
    titleZh: "什么情况下我应该用AI人设而不是真人？",
    titleEn: "When should I use AI personas instead of real people?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/interview/when-use-ai-not-real-people.zh.md",
    filePathEn: "docs/product/faq/interview/when-use-ai-not-real-people.en.md",
  },
  // general (2)
  {
    slug: "ai-recommendation-liability",
    titleZh: "如果AI人设给出的建议是错的，谁负责？",
    titleEn: "If AI personas give wrong recommendations, who's responsible?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/general/ai-recommendation-liability.zh.md",
    filePathEn: "docs/product/faq/general/ai-recommendation-liability.en.md",
  },
  {
    slug: "real-profit-case-studies",
    titleZh: "有人用你们的产品真的赚到钱了吗？",
    titleEn: "Has anyone actually made money using your product?",
    category: "faq",
    descriptionZh: "",
    descriptionEn: "",
    filePathZh: "docs/product/faq/general/real-profit-case-studies.zh.md",
    filePathEn: "docs/product/faq/general/real-profit-case-studies.en.md",
  },
];
