import { prisma } from "@/prisma/prisma";
import { decryptAnalystId } from "../encrypt";

export async function GET(request: Request, { params }: { params: Promise<{ token: string }> }) {
  const token = (await params).token;
  const url = new URL(request.url);
  const isLive = url.searchParams.get("live") === "1";

  if (token.length !== 16) {
    // @TODO[LEGACY] report url generated by analyst/[id]/live page
    try {
      const analystId = await decryptAnalystId(token);
      const report = await prisma.analystReport.findFirstOrThrow({
        where: { analystId },
        orderBy: { createdAt: "asc" },
      });
      // redirect(`/artifacts/report/${report.token}/share`);
      return new Response(null, {
        status: 308,
        headers: {
          Location: `/artifacts/report/${report.token}/share`,
        },
      });
    } catch (error) {
      console.log(error);
      return new Response(null, {
        status: 404,
      });
    }
  }

  return new Response(null, {
    status: 308,
    headers: {
      Location: isLive
        ? `/artifacts/report/${token}/raw?live=1`
        : `/artifacts/report/${token}/share`,
    },
  });
}
