import React from "react";

const coreConcepts = [
  [
    "AI Persona",
    "<strong>(Core Term)</strong> A virtual user simulated by AI, possessing specific demographic traits, behavioral patterns, and psychological motivations. Serves as the primary <strong>research subject</strong> in the system.",
  ],
  [
    "AI Persona (Social Media)",
    "An `AI Persona` synthesized from in-depth analysis of public data like social media. (See Tier 1)",
  ],
  [
    "AI Persona (Deep Interview)",
    "An `AI Persona` with higher fidelity and behavioral consistency, synthesized by the atypica.AI team through <strong>deep interviews</strong> with real people (see Tier 2).",
  ],
  [
    "Human AI Persona (Proprietary)",
    "A private `AI Persona` generated by users through the `AI Persona Import` feature, based on real <strong>enterprise</strong> interview data (see Tier 3).",
  ],
  [
    "Interview",
    "One-on-one deep interview format where an Interviewer AI conducts in-depth dialogue with a single AI Persona to obtain personal insights, emotional understanding, and behavioral motivation analysis.",
  ],
  [
    "Interviewer AI",
    "The AI role responsible for <strong>conducting interviews and asking questions</strong> within features like &quot;Interview Projects&quot;.",
  ],
  [
    "Discussion",
    "Multi-person group discussion format where a moderator guides multiple AI Personas to interact, used to observe viewpoint collisions and simulate group decision-making scenarios. Includes three subtypes: <strong>Focus Group</strong>, <strong>Roundtable</strong>, and <strong>Debate</strong>.",
  ],
  [
    "Study Expert",
    "<strong>(Core Technology)</strong> One of atypica.AI&apos;s core AI technologies, as important as `AI Persona`. Built on atypica.AI team&apos;s reasoning model, responsible for leading research planning, conducting interviews, and deep analysis.",
  ],
  [
    "Sage",
    "An evolvable domain expert agent that achieves continuous learning and knowledge evolution through memory documents, knowledge gap tracking, and supplementary interview mechanisms.",
  ],
  [
    "AI Persona Import",
    "A core functional module for automatically analyzing and generating an `AI Persona` by uploading files such as interview transcripts.",
  ],
  [
    "Interview Project",
    "A research project that users can create and manage, where they can conduct interviews with `AI Personas` or real users.",
  ],
];

const tiers = [
  {
    title: "Tier 1: AI Persona (Social Media)",
    source: "Source: Synthesized from public data like social media",
    desc: "Synthesized from in-depth analysis and pattern extraction of public data. It has more defined behavioral patterns and characteristics, making it suitable for more specific market analysis.",
  },
  {
    title: "Tier 2: AI Persona (Deep Interview)",
    source: "Source: Professional Cognitive Modeling",
    desc: "High-quality, high-precision personas built by the atypica.AI team through deep interviews and professional cognitive modeling. They exhibit high consistency in cognitive patterns, emotional responses, and decision-making logic, enabling deep business research by simulating complex consumer behaviors.",
  },
  {
    title: "Tier 3: Human AI Persona (Proprietary)",
    source: "Source: User-Uploaded <strong>Enterprise</strong> Private Data",
    desc: "AI Personas generated by users through the `AI Persona Import` feature, uploading real <strong>enterprise</strong> interview transcripts. Their key feature is <strong>privacy</strong>; they are built exclusively from user-provided private data and are not searchable or usable by others, ensuring business data security. Fidelity depends directly on the quality of the uploaded interview data.",
  },
];

const roles = [
  {
    title: "AI Persona",
    position: "Research subject, interviewee, discussion participant",
    capability: "Authenticity simulation, diverse sources, tiered system",
    usage: "Interview responses, discussion interaction",
  },
  {
    title: "Interviewer AI",
    position: "Interview conductor, questioner",
    capability: "Deep probing, dialogue guidance, structured interviews",
    usage: "One-on-one in-depth interviews, insight mining",
  },
  {
    title: "Moderator AI",
    position: "Discussion moderator, coordinator",
    capability: "Multi-format moderation, interaction facilitation, pace control",
    usage: "Focus groups, roundtables, debates",
  },
  {
    title: "Sage",
    position: "Evolvable domain expert agent",
    capability: "Memory as expertise, continuous evolution, full traceability",
    usage: "Memory documents, knowledge gap tracking, supplementary interviews",
    isCore: true,
  },
];

export const GlossaryEN: React.FC = () => {
  return (
    <div className="max-w-7xl mx-auto px-6 py-12 font-sans">
      <header className="text-center mb-12">
        <h1 className="text-3xl font-bold mb-2 font-mono tracking-tighter">
          [ atypica.AI Glossary ]
        </h1>
        <p className="text-gray-600 dark:text-gray-400">
          A lexicon to synchronize communication protocols among all agents, human or otherwise.
        </p>
      </header>

      <div className="space-y-16">
        <section>
          <h2 className="text-2xl font-bold mb-6 border-b pb-3 font-mono">
            &#123;/* 1. Core Concepts */&#125;
          </h2>
          <div className="overflow-x-auto">
            <table className="min-w-full border-collapse border">
              <thead>
                <tr>
                  <th className="px-4 py-3 text-left text-sm font-semibold border-b w-1/3">Term</th>
                  <th className="px-4 py-3 text-left text-sm font-semibold border-b">
                    Description
                  </th>
                </tr>
              </thead>
              <tbody>
                {coreConcepts.map(([term, desc], i) => (
                  <tr key={i}>
                    <td className="px-4 py-3 border-b align-top">
                      <code className="font-semibold text-base">{term}</code>
                    </td>
                    <td className="px-4 py-3 border-b" dangerouslySetInnerHTML={{ __html: desc }} />
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-8 font-mono border-b pb-3">
            &#123;/* 2. AI Persona Tiers */&#125;
          </h2>
          <p className="mb-8 text-gray-600 dark:text-gray-400">
            `AI Personas` are classified into tiers based on their data source, construction method,
            and precision. Higher tiers represent greater realism and complexity in behavioral
            simulation.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {tiers.map((tier, i) => (
              <div key={i} className="border rounded-lg p-6">
                <h3 className="text-xl font-bold mb-2 font-mono">{tier.title}</h3>
                <p
                  className="text-sm font-semibold text-gray-600 dark:text-gray-400 mb-4"
                  dangerouslySetInnerHTML={{ __html: tier.source }}
                />
                <p
                  className="text-gray-600 dark:text-gray-400"
                  dangerouslySetInnerHTML={{ __html: tier.desc }}
                />
              </div>
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-8 font-mono border-b pb-3">
            &#123;/* 3. Simulated Human Agent Roles */&#125;
          </h2>
          <p className="mb-8 text-gray-600 dark:text-gray-400">
            The system includes multiple agent roles that simulate human behavior, each serving
            distinct functions:
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {roles.map((role, i) => (
              <div key={i} className="border rounded-lg p-6">
                <h3 className="text-xl font-semibold mb-3">{role.title}</h3>
                <p className="mb-2">
                  <span className="font-semibold text-gray-600 dark:text-gray-400">Role:</span>
                  <span className="ml-2">{role.position}</span>
                </p>
                <p className="mb-2">
                  <span className="font-semibold text-gray-600 dark:text-gray-400">
                    Core Capabilities:
                  </span>
                  <span className="ml-2">{role.capability}</span>
                </p>
                <p className="mb-2">
                  <span className="font-semibold text-gray-600 dark:text-gray-400">
                    {role.isCore ? "Core Technology" : "Use Cases"}:
                  </span>
                  <span className="ml-2">{role.usage}</span>
                </p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
};
