import { productRnDSystem } from "@/ai/prompt/study/productRnD";
import {
  audienceCallTool,
  generateReportTool,
  scoutSocialTrendsTool,
  toolCallError,
  webFetchTool,
} from "@/ai/tools/tools";
import { AgentToolConfigArgs, StatReporter, ToolName } from "@/ai/tools/types";
import type { Analyst, UserChatExtra } from "@/prisma/client";
import { Locale } from "next-intl";
import { Logger } from "pino";
import { AgentRequestConfig } from "../baseAgentRequest";

/**
 * Parameters for creating product R&D agent configuration
 */
export interface ProductRnDAgentConfigParams {
  userId: number;
  studyUserChatId: number;
  analyst: Analyst;
  userChatExtra: UserChatExtra;
  locale: Locale;
  logger: Logger;
  statReport: StatReporter;
  toolAbortController: AbortController;
}

// 只是当前 agent 需要的 tools
type TOOLS = ReturnType<typeof buildProductRnDTools>;

/**
 * Create product R&D agent configuration
 *
 * Product R&D Agent features:
 * - Product innovation opportunity discovery
 * - 6 specialized tools focused on social trends and audience feedback
 * - Uses scoutSocialTrends instead of webSearch
 * - Emphasizes cross-domain inspiration (avoiding filter bubbles)
 * - User feedback driven (audienceCall) for validation
 * - Uses advanced model (claude-3-7-sonnet)
 */
export async function createProductRnDAgentConfig(
  params: ProductRnDAgentConfigParams,
): Promise<AgentRequestConfig<ReturnType<typeof buildProductRnDTools>>> {
  const { studyUserChatId, userId, locale, logger, statReport, toolAbortController } = params;

  // =============================================================================
  // 1. Build tools
  // =============================================================================

  const agentToolArgs: AgentToolConfigArgs = {
    locale,
    abortSignal: toolAbortController.signal,
    statReport,
    logger: logger,
  };

  const tools = buildProductRnDTools({
    studyUserChatId,
    userId,
    agentToolArgs,
  });

  // =============================================================================
  // 2. Build system prompt
  // =============================================================================

  const systemPrompt = productRnDSystem({ locale });

  // =============================================================================
  // 3. Return configuration
  // =============================================================================

  return {
    model: "claude-3-7-sonnet", // Use advanced model
    systemPrompt,
    tools,

    specialHandlers: {
      /**
       * customPrepareStep: Dynamic tool control based on message history
       * - Scan message history to detect if report has been generated
       * - Restrict tools after report generation
       */
      customPrepareStep: async ({ messages }) => {
        // Check if report has been generated by scanning message history
        let reportGenerated = false;
        for (const message of messages) {
          if (message.role === "tool") {
            for (const part of message.content) {
              if (part.toolName === ToolName.generateReport) {
                reportGenerated = true;
                break;
              }
            }
          }
          if (reportGenerated) break;
        }

        const activeTools: (keyof TOOLS)[] | undefined = reportGenerated
          ? [ToolName.generateReport, ToolName.toolCallError]
          : undefined;

        return { messages, activeTools };
      },

      // Note: customOnStepFinish removed - all notifications handled universally in base
      // - generateReport completion → notifyReportCompletion + trackEvent (in base)
    },
  };
}

/**
 * Build product R&D tools focused on innovation discovery
 */
function buildProductRnDTools(params: {
  studyUserChatId: number;
  userId: number;
  agentToolArgs: AgentToolConfigArgs;
}) {
  const { studyUserChatId, userId, agentToolArgs } = params;

  return {
    [ToolName.webFetch]: webFetchTool({ locale: agentToolArgs.locale }),
    [ToolName.audienceCall]: audienceCallTool({ ...agentToolArgs }),
    [ToolName.scoutSocialTrends]: scoutSocialTrendsTool({ userId, ...agentToolArgs }),
    [ToolName.generateReport]: generateReportTool({ studyUserChatId, ...agentToolArgs }),
    [ToolName.toolCallError]: toolCallError,
  };
}
