import type { Doc } from "../types";

// Features and competitor comparisons (44 docs: 10 features + 34 competitors)
export const docs: Doc[] = [
  {
    slug: "interview-vs-discussion",
    titleZh: "Interview vs Discussion：什么时候用哪个？",
    titleEn: "Interview vs Discussion: Which One Should You Use?",
    category: "feature",
    descriptionZh: "深度对比 Interview Chat 和 Discussion Chat 的差异、适用场景和能力边界",
    descriptionEn:
      "In-depth comparison of Interview Chat and Discussion Chat: differences, use cases, and capabilities",
    filePathZh: "docs/product/features/interview-vs-discussion.zh.md",
    filePathEn: "docs/product/features/interview-vs-discussion.en.md",
  },
  {
    slug: "scout-agent",
    titleZh: "Scout Agent：社交媒体深度观察",
    titleEn: "Scout Agent: Deep Social Media Observation",
    category: "feature",
    descriptionZh: "通过沉浸式观察社交媒体内容，理解用户群体的生活方式、价值观和精神世界",
    descriptionEn:
      "Understand user groups' lifestyles, values, and mindsets through immersive social media observation",
    filePathZh: "docs/product/features/scout-agent.zh.md",
    filePathEn: "docs/product/features/scout-agent.en.md",
  },
  {
    slug: "ai-persona-tiers",
    titleZh: "AI Persona 三层体系架构",
    titleEn: "AI Persona Three-Tier System",
    category: "feature",
    descriptionZh: "基于一致性科学的四级分层 Persona 库，构建高质量 AI 人设",
    descriptionEn:
      "Four-tier persona library based on consistency science for building high-quality AI personas",
    filePathZh: "docs/product/features/ai-persona-tiers.zh.md",
    filePathEn: "docs/product/features/ai-persona-tiers.en.md",
  },
  {
    slug: "plan-mode",
    titleZh: "Plan Mode：让 AI 先懂你要什么",
    titleEn: "Plan Mode: Let AI Understand What You Want First",
    category: "feature",
    descriptionZh: "对话即规划，AI 自动判断研究类型，展示完整计划，一键确认开始",
    descriptionEn:
      "Conversation is planning - AI auto-determines research type, shows complete plan, one-click confirmation",
    filePathZh: "docs/product/features/plan-mode.zh.md",
    filePathEn: "docs/product/features/plan-mode.en.md",
  },
  {
    slug: "memory-system",
    titleZh: "Memory System：AI 的渐进式学习系统",
    titleEn: "Memory System: Progressive Learning for AI",
    category: "feature",
    descriptionZh: "持久化记忆系统，让 AI 越用越懂你，无需重复询问",
    descriptionEn:
      "Persistent memory system that helps AI understand you better over time without repetitive questions",
    filePathZh: "docs/product/features/memory-system.zh.md",
    filePathEn: "docs/product/features/memory-system.en.md",
  },
  {
    slug: "fast-insight-agent",
    titleZh: "Fast Insight：播客优先自动化",
    titleEn: "Fast Insight: Podcast-First Automation",
    category: "feature",
    descriptionZh: "从研究需求到播客内容，一条龙自动化，数小时完成",
    descriptionEn:
      "End-to-end automation from research needs to podcast content, completed in hours",
    filePathZh: "docs/product/features/fast-insight-agent.zh.md",
    filePathEn: "docs/product/features/fast-insight-agent.en.md",
  },
  {
    slug: "product-rnd-agent",
    titleZh: "Product R&D Agent：产品研发智能体",
    titleEn: "Product R&D Agent: Product Development Intelligence",
    category: "feature",
    descriptionZh: "从市场趋势到用户需求，为产品创新提供全方位研究支持",
    descriptionEn:
      "Comprehensive research support for product innovation, from market trends to user needs",
    filePathZh: "docs/product/features/product-rnd-agent.zh.md",
    filePathEn: "docs/product/features/product-rnd-agent.en.md",
  },
  {
    slug: "reference-attachments",
    titleZh: "参考研究 + 文件附件",
    titleEn: "Reference Studies + File Attachments",
    category: "feature",
    descriptionZh: "通过参考研究和文件附件，让 AI 基于完整上下文进行深度分析",
    descriptionEn:
      "Enable AI to perform deep analysis based on complete context through reference studies and file attachments",
    filePathZh: "docs/product/features/reference-attachments.zh.md",
    filePathEn: "docs/product/features/reference-attachments.en.md",
  },
  {
    slug: "mcp-integration",
    titleZh: "MCP 集成能力",
    titleEn: "MCP Integration Capabilities",
    category: "feature",
    descriptionZh: "通过 MCP 协议打破数据孤岛，让 AI 接入企业内部工具和数据源",
    descriptionEn:
      "Break data silos through MCP protocol, connecting AI to enterprise internal tools and data sources",
    filePathZh: "docs/product/features/mcp-integration.zh.md",
    filePathEn: "docs/product/features/mcp-integration.en.md",
  },
  {
    slug: "sage-system",
    titleZh: "Sage：可进化的专家系统",
    titleEn: "Sage: Evolving Expert System",
    category: "feature",
    descriptionZh: "通过主动学习和知识积累，Sage 系统会随着使用不断进化",
    descriptionEn:
      "Through active learning and knowledge accumulation, the Sage system evolves with usage",
    filePathZh: "docs/product/features/sage-system.zh.md",
    filePathEn: "docs/product/features/sage-system.en.md",
  },

  // Competitor Comparisons - AI Products (22)
  {
    slug: "atypica-vs-listen-labs",
    titleZh: "atypica.AI vs Listen Labs：AI 驱动的用户研究平台对比",
    titleEn: "atypica.AI vs Listen Labs",
    category: "competitor",
    descriptionZh: "AI 访谈工具 vs 多场景研究平台，都使用 AI 模拟用户进行研究",
    descriptionEn:
      "AI interview tool vs multi-scenario research platform, both using AI to simulate users",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-listen-labs.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-listen-labs.en.md",
  },
  {
    slug: "atypica-vs-claude-projects",
    titleZh: "atypica.AI vs Claude Projects：商业研究智能体 vs 通用知识助手",
    titleEn: "atypica.AI vs Claude Projects",
    category: "competitor",
    descriptionZh: "通用知识助手 vs 商业研究智能体，同样基于 Claude 但定位不同",
    descriptionEn:
      "General knowledge assistant vs business research agent, both built on Claude but different positioning",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-claude-projects.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-claude-projects.en.md",
  },
  {
    slug: "atypica-vs-usertesting",
    titleZh: "atypica.AI vs UserTesting：AI 模拟 vs 真人测试",
    titleEn: "atypica.AI vs UserTesting",
    category: "competitor",
    descriptionZh: "真人测试平台 vs AI 研究加速器，节省 80-85% 成本",
    descriptionEn: "Real human testing platform vs AI research accelerator, save 80-85% cost",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-usertesting.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-usertesting.en.md",
  },
  {
    slug: "atypica-vs-surveymonkey",
    titleZh: "atypica.AI vs SurveyMonkey：AI 对话 vs 问卷调研",
    titleEn: "atypica.AI vs SurveyMonkey",
    category: "competitor",
    descriptionZh: "量化问卷调研 vs 质性对话研究，理解'为什么' vs '多少人'",
    descriptionEn:
      "Quantitative survey research vs qualitative conversational research, 'why' vs 'how many'",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-surveymonkey.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-surveymonkey.en.md",
  },
  {
    slug: "atypica-vs-notebooklm",
    titleZh: "atypica.AI vs NotebookLM：主动研究 vs 被动播客",
    titleEn: "atypica.AI vs NotebookLM",
    category: "competitor",
    descriptionZh: "文档播客生成 vs 研究+播客平台，被动转化 vs 主动研究",
    descriptionEn:
      "Document-to-podcast generation vs research + podcast platform, passive conversion vs active research",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-notebooklm.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-notebooklm.en.md",
  },
  {
    slug: "atypica-vs-otter-ai",
    titleZh: "atypica.AI vs Otter.ai：主观洞察 vs 客观记录",
    titleEn: "atypica.AI vs Otter.ai",
    category: "competitor",
    descriptionZh: "会议转录 vs 用户研究，记录'说了什么' vs 理解'为什么'",
    descriptionEn:
      "Meeting transcription vs user research, recording 'what was said' vs understanding 'why'",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-otter-ai.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-otter-ai.en.md",
  },
  {
    slug: "atypica-vs-traditional-research",
    titleZh: "atypica.AI vs 传统调研公司：全面对比",
    titleEn: "atypica.AI vs Traditional Research",
    category: "competitor",
    descriptionZh: "AI 模拟 vs 真人招募，数小时 vs 数周",
    descriptionEn: "AI simulation vs human recruitment, hours vs weeks",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-traditional-research.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-traditional-research.en.md",
  },
  {
    slug: "atypica-vs-deepsona",
    titleZh: "atypica vs Deepsona：全场景研究 vs 预测性建模",
    titleEn: "atypica vs Deepsona",
    category: "competitor",
    descriptionZh: "全场景用户研究平台 vs 预测性市场研究工具",
    descriptionEn: "Full-scenario research vs predictive modeling",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-deepsona.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-deepsona.en.md",
  },
  {
    slug: "atypica-vs-maze",
    titleZh: "atypica vs Maze：用户洞察平台 vs 产品发现平台",
    titleEn: "atypica vs Maze",
    category: "competitor",
    descriptionZh: "深度洞察和战略 vs 原型测试和热图",
    descriptionEn: "User insights vs product discovery",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-maze.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-maze.en.md",
  },
  {
    slug: "atypica-vs-roundtable",
    titleZh: "atypica vs Roundtable：用户研究平台 vs 问卷防欺诈工具",
    titleEn: "atypica vs Roundtable",
    category: "competitor",
    descriptionZh: "用户研究平台 vs 问卷防欺诈工具",
    descriptionEn: "User research platform vs survey fraud prevention",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-roundtable.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-roundtable.en.md",
  },
  {
    slug: "atypica-vs-sprig",
    titleZh: "atypica vs Sprig：全场景研究 vs 产品体验反馈",
    titleEn: "atypica vs Sprig",
    category: "competitor",
    descriptionZh: "全场景研究 vs 产品体验反馈",
    descriptionEn: "Full-scenario research vs product experience feedback",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-sprig.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-sprig.en.md",
  },
  {
    slug: "atypica-vs-yabble",
    titleZh: "atypica vs Yabble：全场景研究 vs Virtual Audiences问卷",
    titleEn: "atypica vs Yabble",
    category: "competitor",
    descriptionZh: "全场景研究 vs Virtual Audiences问卷",
    descriptionEn: "Full-scenario research vs virtual audiences surveys",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-yabble.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-yabble.en.md",
  },
  {
    slug: "atypica-vs-persona-panels",
    titleZh: "atypica vs PersonaPanels：AI研究平台 vs 合成受访者面板",
    titleEn: "atypica vs PersonaPanels",
    category: "competitor",
    descriptionZh: "AI研究平台 vs 合成受访者面板",
    descriptionEn: "AI research platform vs synthetic respondent panels",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-persona-panels.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-persona-panels.en.md",
  },
  {
    slug: "atypica-vs-perplexity",
    titleZh: "atypica vs Perplexity：用户研究平台 vs AI深度搜索引擎",
    titleEn: "atypica vs Perplexity",
    category: "competitor",
    descriptionZh: "用户研究平台 vs AI深度搜索引擎",
    descriptionEn: "User research platform vs AI deep search engine",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-perplexity.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-perplexity.en.md",
  },
  {
    slug: "atypica-vs-wynter",
    titleZh: "atypica vs Wynter：深度用户研究 vs 消息测试",
    titleEn: "atypica vs Wynter",
    category: "competitor",
    descriptionZh: "深度用户研究 vs 消息测试",
    descriptionEn: "Deep user research vs message testing",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-wynter.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-wynter.en.md",
  },
  {
    slug: "atypica-vs-synthetic-research-tools",
    titleZh: "atypica vs 合成研究工具：全场景研究 vs 自动化测试",
    titleEn: "atypica vs Synthetic Research Tools",
    category: "competitor",
    descriptionZh: "全场景研究 vs 自动化测试",
    descriptionEn: "Full-scenario research vs automated testing",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-synthetic-research-tools.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-synthetic-research-tools.en.md",
  },
  {
    slug: "atypica-vs-qualtrics",
    titleZh: "atypica vs Qualtrics：AI用户研究 vs 企业级调研平台",
    titleEn: "atypica vs Qualtrics",
    category: "competitor",
    descriptionZh: "AI用户研究 vs 企业级调研平台",
    descriptionEn: "AI user research vs enterprise research platform",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-qualtrics.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-qualtrics.en.md",
  },
  {
    slug: "atypica-vs-delve-ai",
    titleZh: "atypica vs Delve AI：用户研究平台 vs Persona生成工具",
    titleEn: "atypica vs Delve AI",
    category: "competitor",
    descriptionZh: "用户研究平台 vs Persona生成工具",
    descriptionEn: "User research platform vs persona generation tool",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-delve-ai.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-delve-ai.en.md",
  },
  {
    slug: "atypica-vs-synthetic-users",
    titleZh: "atypica vs Synthetic Users：用户研究 vs 产品测试",
    titleEn: "atypica vs Synthetic Users",
    category: "competitor",
    descriptionZh: "用户研究 vs 产品测试",
    descriptionEn: "User research vs product testing",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-synthetic-users.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-synthetic-users.en.md",
  },
  {
    slug: "atypica-vs-user-testing",
    titleZh: "atypica vs UserTesting：用户研究平台 vs 真人视频测试",
    titleEn: "atypica vs UserTesting",
    category: "competitor",
    descriptionZh: "用户研究平台 vs 真人视频测试",
    descriptionEn: "User research platform vs real-person video testing",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-user-testing.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-user-testing.en.md",
  },
  {
    slug: "atypica-vs-ai-persona-tools",
    titleZh: "atypica vs AI Persona工具：全场景研究 vs Persona生成器",
    titleEn: "atypica vs AI Persona Tools",
    category: "competitor",
    descriptionZh: "全场景研究 vs Persona生成器",
    descriptionEn: "Full-scenario research vs persona generators",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-ai-persona-tools.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-ai-persona-tools.en.md",
  },
  {
    slug: "atypica-vs-dovetail",
    titleZh: "atypica vs Dovetail：用户研究平台 vs 洞察管理工具",
    titleEn: "atypica vs Dovetail",
    category: "competitor",
    descriptionZh: "用户研究平台 vs 洞察管理工具",
    descriptionEn: "User research platform vs insights management tool",
    filePathZh: "docs/product/competitors/ai-products/atypica-vs-dovetail.zh.md",
    filePathEn: "docs/product/competitors/ai-products/atypica-vs-dovetail.en.md",
  },

  // Competitor Comparisons - Traditional (12)
  {
    slug: "atypica-vs-mckinsey",
    titleZh: "atypica vs McKinsey：AI研究工具 vs 顶级战略咨询",
    titleEn: "atypica vs McKinsey",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 顶级战略咨询",
    descriptionEn: "AI research tool vs top-tier strategy consulting",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-mckinsey.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-mckinsey.en.md",
  },
  {
    slug: "atypica-vs-bcg",
    titleZh: "atypica vs BCG：AI用户研究 vs 战略咨询",
    titleEn: "atypica vs BCG",
    category: "competitor",
    descriptionZh: "AI用户研究 vs 战略咨询",
    descriptionEn: "AI user research vs strategy consulting",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-bcg.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-bcg.en.md",
  },
  {
    slug: "atypica-vs-bain",
    titleZh: "atypica vs Bain：AI研究工具 vs 顶级战略咨询",
    titleEn: "atypica vs Bain",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 顶级战略咨询",
    descriptionEn: "AI research tool vs top-tier strategy consulting",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-bain.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-bain.en.md",
  },
  {
    slug: "atypica-vs-nielsen",
    titleZh: "atypica vs Nielsen：AI研究工具 vs 消费数据巨头",
    titleEn: "atypica vs Nielsen",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 消费数据巨头",
    descriptionEn: "AI research tool vs consumer data giant",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-nielsen.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-nielsen.en.md",
  },
  {
    slug: "atypica-vs-kantar",
    titleZh: "atypica vs Kantar：AI研究工具 vs 全球洞察巨头",
    titleEn: "atypica vs Kantar",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 全球洞察巨头",
    descriptionEn: "AI research tool vs global insights giant",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-kantar.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-kantar.en.md",
  },
  {
    slug: "atypica-vs-ipsos",
    titleZh: "atypica vs Ipsos：AI研究工具 vs 全球研究巨头",
    titleEn: "atypica vs Ipsos",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 全球研究巨头",
    descriptionEn: "AI research tool vs global research giant",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-ipsos.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-ipsos.en.md",
  },
  {
    slug: "atypica-vs-gfk",
    titleZh: "atypica vs GfK：AI研究工具 vs 德国市场研究巨头",
    titleEn: "atypica vs GfK",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 德国市场研究巨头",
    descriptionEn: "AI research tool vs German market research giant",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-gfk.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-gfk.en.md",
  },
  {
    slug: "atypica-vs-gartner",
    titleZh: "atypica vs Gartner：AI研究工具 vs 技术研究分析",
    titleEn: "atypica vs Gartner",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 技术研究分析",
    descriptionEn: "AI research tool vs technology research and analysis",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-gartner.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-gartner.en.md",
  },
  {
    slug: "atypica-vs-forrester",
    titleZh: "atypica vs Forrester：AI研究工具 vs 技术研究咨询",
    titleEn: "atypica vs Forrester",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 技术研究咨询",
    descriptionEn: "AI research tool vs technology research and consulting",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-forrester.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-forrester.en.md",
  },
  {
    slug: "atypica-vs-idc",
    titleZh: "atypica vs IDC：AI研究工具 vs IT市场研究",
    titleEn: "atypica vs IDC",
    category: "competitor",
    descriptionZh: "AI研究工具 vs IT市场研究",
    descriptionEn: "AI research tool vs IT market research",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-idc.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-idc.en.md",
  },
  {
    slug: "atypica-vs-roland-berger",
    titleZh: "atypica vs Roland Berger：AI研究工具 vs 欧洲战略咨询",
    titleEn: "atypica vs Roland Berger",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 欧洲战略咨询",
    descriptionEn: "AI research tool vs European strategy consulting",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-roland-berger.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-roland-berger.en.md",
  },
  {
    slug: "atypica-vs-ctr",
    titleZh: "atypica vs 索福瑞/CTR：AI研究工具 vs 中国媒体测量",
    titleEn: "atypica vs CTR",
    category: "competitor",
    descriptionZh: "AI研究工具 vs 中国媒体测量",
    descriptionEn: "AI research tool vs China media measurement",
    filePathZh: "docs/product/competitors/traditional/atypica-vs-ctr.zh.md",
    filePathEn: "docs/product/competitors/traditional/atypica-vs-ctr.en.md",
  },
];
