"use server";
import { StatReporter } from "@/ai/tools/types";
import { generateInterviewPlan } from "@/app/(sage)/processing/followup";
import { discoverKnowledgeGapsFromSageChats } from "@/app/(sage)/processing/gaps";
import { extractKnowledgeFromSources } from "@/app/(sage)/processing/memory";
import { processSageSources } from "@/app/(sage)/processing/sources";
import type { SageExtra, SageInterviewExtra, SageKnowledgeGapSeverity } from "@/app/(sage)/types";
import { VALID_LOCALES } from "@/i18n/routing";
import { rootLogger } from "@/lib/logging";
import { withAuth } from "@/lib/request/withAuth";
import type { ServerActionResult } from "@/lib/serverAction";
import { createUserChat } from "@/lib/userChat/lib";
import type { SageInterview, UserChat } from "@/prisma/client";
import { prisma } from "@/prisma/prisma";
import { mergeExtra } from "@/prisma/utils";
import { waitUntil } from "@vercel/functions";
import { Locale } from "next-intl";
import { getLocale } from "next-intl/server";
import { revalidatePath } from "next/cache";

/**
 * Create a supplementary interview to fill knowledge gaps
 */
export async function createSupplementaryInterview(sageId: number): Promise<
  ServerActionResult<{
    interview: SageInterview;
    userChat: UserChat;
  }>
> {
  return withAuth(async (user) => {
    try {
      // Check ownership and get sage info needed for interview plan
      const sage = await prisma.sage.findUnique({
        where: { id: sageId },
        select: {
          userId: true,
          name: true,
          domain: true,
          expertise: true,
        },
      });

      if (!sage) {
        return {
          success: false,
          message: "Sage not found",
          code: "not_found",
        };
      }

      if (sage.userId !== user.id) {
        return {
          success: false,
          message: "Unauthorized",
          code: "unauthorized",
        };
      }

      const locale = await getLocale();

      // Get pending knowledge gaps
      const pendingGaps = await prisma.sageKnowledgeGap.findMany({
        where: {
          sageId,
          resolvedAt: null,
        },
        select: {
          area: true,
          description: true,
          severity: true,
          impact: true,
        },
        orderBy: [{ severity: "desc" }, { createdAt: "asc" }],
      });

      if (pendingGaps.length === 0) {
        return {
          success: false,
          message: locale === "zh-CN" ? "没有待解决的知识空白" : "No pending knowledge gaps",
          code: "forbidden",
        };
      }

      // Convert to format expected by generateInterviewPlan
      const fullKnowledgeGaps = pendingGaps.map((gap) => ({
        area: gap.area,
        severity: gap.severity as SageKnowledgeGapSeverity,
        description: gap.description,
        impact: gap.impact,
        suggestedQuestions: [], // Will be generated by AI
      }));

      // Generate interview plan
      const interviewPlan = await generateInterviewPlan({
        sage: {
          name: sage.name,
          domain: sage.domain,
          expertise: sage.expertise as string[],
        },
        knowledgeGaps: fullKnowledgeGaps,
        locale,
      });

      // Create UserChat for interview
      const userChat = await createUserChat({
        userId: user.id,
        kind: "sageSession",
        title: `Interview: ${sage.name}`,
      });

      // Create SageInterview
      const interview = await prisma.sageInterview.create({
        data: {
          sageId,
          userChatId: userChat.id,
          extra: {
            startsAt: Date.now(),
            ongoing: true,
            interviewPlan,
          } as SageInterviewExtra,
        },
      });

      rootLogger.info(`Created supplementary interview ${interview.id} for sage ${sageId}`);

      return {
        success: true,
        data: { interview, userChat },
      };
    } catch (error) {
      rootLogger.error(`Failed to create supplementary interview: ${error}`);
      return {
        success: false,
        message: "Failed to create supplementary interview",
        code: "internal_server_error",
      };
    }
  });
}

/**
 * re-Process all sources and extract knowledge
 * 因为 source 支持删除，所以就算所有 sources 都被 parse 了，这个过程还是可以重新运行
 */
export async function reProcessSageSourcesAndExtractKnoledge(
  sageId: number,
): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    const sage = await prisma.sage
      .findUniqueOrThrow({
        where: {
          id: sageId,
          userId: user.id,
        },
        select: { id: true, token: true, extra: true },
      })
      .then(({ extra, ...sage }) => ({ ...sage, extra: extra as SageExtra }));

    // 超过 30 分钟可以重新开始
    if (sage.extra.processing && Date.now() - sage.extra.processing.startsAt < 30 * 60 * 1000) {
      return {
        success: false,
        message: "Sage is processing",
      };
    }

    const locale = await getLocale();
    const logger = rootLogger.child({ sageId });
    const statReport: StatReporter = (async (dimension, value, extra) => {
      rootLogger.info({
        msg: `[LIMITED FREE] statReport: ${dimension}=${value}`,
        extra,
        note: "extractKnowledgeOnly is currently free - tokens not deducted",
      });
    }) as StatReporter;
    const abortSignal = new AbortSignal();

    waitUntil(
      (async () => {
        await mergeExtra({
          tableName: "Sage",
          id: sage.id,
          extra: { processing: { startsAt: Date.now() }, error: null } satisfies SageExtra,
        });
        try {
          // 1. process sources
          await processSageSources({ sageId, logger, statReport, abortSignal });
          // 2. extract knowledge
          await extractKnowledgeFromSources({ sageId, locale, logger, statReport, abortSignal });
          // 3. complete
          await mergeExtra({
            tableName: "Sage",
            id: sage.id,
            extra: { processing: false } satisfies SageExtra,
          });
        } catch (error) {
          await mergeExtra({
            tableName: "Sage",
            id: sage.id,
            extra: { processing: false, error: (error as Error).message } satisfies SageExtra,
          });
          // throw error;  // do not throw error
        }
      })(),
    );

    revalidatePath(`/sage/${sage.token}`);
    return { success: true, data: undefined };
  });
}

/**
 * Batch analyze recent sage chats for knowledge gaps
 * Triggered manually by expert in Sage Chats management page
 */
export async function discoverKnowledgeGapsFromSageChatsAction({
  sageId,
  limit = 20,
}: {
  sageId: number;
  limit?: number;
}): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    const sage = await prisma.sage
      .findUniqueOrThrow({
        where: { id: sageId, userId: user.id },
        select: { id: true, token: true, locale: true, extra: true },
      })
      .then(({ extra, ...sage }) => ({ ...sage, extra: extra as SageExtra }));

    // 超过 30 分钟可以重新开始
    if (sage.extra.processing && Date.now() - sage.extra.processing.startsAt < 30 * 60 * 1000) {
      return {
        success: false,
        message: "Sage is processing",
      };
    }

    const locale = VALID_LOCALES.includes(sage.locale as Locale)
      ? (sage.locale as Locale)
      : await getLocale();
    const logger = rootLogger.child({ sageId });
    const statReport: StatReporter = (async (dimension, value, extra) => {
      rootLogger.info({
        msg: `[LIMITED FREE] statReport: ${dimension}=${value}`,
        extra,
        note: "extractKnowledgeOnly is currently free - tokens not deducted",
      });
    }) as StatReporter;
    const abortSignal = new AbortController().signal;

    waitUntil(
      (async () => {
        await mergeExtra({
          tableName: "Sage",
          id: sage.id,
          extra: { processing: { startsAt: Date.now() }, error: null } satisfies SageExtra,
        });
        try {
          await discoverKnowledgeGapsFromSageChats({
            sageId,
            limit,
            locale,
            logger,
            statReport,
            abortSignal,
          });
          await mergeExtra({
            tableName: "Sage",
            id: sage.id,
            extra: { processing: false } satisfies SageExtra,
          });
        } catch (error) {
          await mergeExtra({
            tableName: "Sage",
            id: sage.id,
            extra: { processing: false, error: (error as Error).message } satisfies SageExtra,
          });
          // throw error;  // do not throw error
        }
      })(),
    );

    revalidatePath(`/sage/${sage.token}`);
    return { success: true, data: undefined };
  });
}

/**
 * Update sage avatar
 */
export async function updateSageAvatar(
  sageId: number,
  avatarUrl: string,
): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    // Check ownership and get token for revalidation
    const sage = await prisma.sage.findUnique({
      where: { id: sageId },
      select: {
        userId: true,
        token: true,
      },
    });

    if (!sage) {
      return {
        success: false,
        message: "Sage not found",
        code: "not_found",
      };
    }

    if (sage.userId !== user.id) {
      return {
        success: false,
        message: "Not authorized",
        code: "forbidden",
      };
    }

    await prisma.sage.update({
      where: { id: sageId },
      data: {
        avatar: { url: avatarUrl },
      },
    });

    revalidatePath(`/sage/${sage.token}`);
    revalidatePath(`/sage/profile/${sage.token}`);

    return { success: true, data: undefined };
  });
}
