"use server";
import { generateInterviewPlan } from "@/app/(sage)/processing/followup";
import { analyzeKnowledgeOnly } from "@/app/(sage)/processing/gaps";
import { extractKnowledgeOnly } from "@/app/(sage)/processing/memory";
import { processSourcesOnly } from "@/app/(sage)/processing/sources";
import type { SageInterviewExtra, SageKnowledgeGapSeverity } from "@/app/(sage)/types";
import { rootLogger } from "@/lib/logging";
import { withAuth } from "@/lib/request/withAuth";
import type { ServerActionResult } from "@/lib/serverAction";
import { createUserChat } from "@/lib/userChat/lib";
import type { SageInterview, UserChat } from "@/prisma/client";
import { prisma } from "@/prisma/prisma";
import { waitUntil } from "@vercel/functions";
import { getLocale } from "next-intl/server";
import { revalidatePath } from "next/cache";

// ===== Knowledge Analysis =====

/**
 * Analyze sage knowledge completeness
 */
export async function analyzeSageKnowledge(sageId: number): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    // Check ownership and get token for revalidation
    const sage = await prisma.sage.findUnique({
      where: { id: sageId },
      select: {
        userId: true,
        token: true,
      },
    });

    if (!sage) {
      return {
        success: false,
        message: "Sage not found",
        code: "not_found",
      };
    }

    if (sage.userId !== user.id) {
      return {
        success: false,
        message: "Unauthorized",
        code: "unauthorized",
      };
    }

    // Check if memory document exists
    const memoryDoc = await prisma.sageMemoryDocument.findFirst({
      where: { sageId },
      select: { id: true },
    });

    if (!memoryDoc) {
      return {
        success: false,
        message: "Memory document not ready",
        code: "forbidden",
      };
    }

    const locale = await getLocale();

    // Trigger background analysis only
    waitUntil(analyzeKnowledgeOnly({ sageId, locale }));

    revalidatePath(`/sage/${sage.token}`);

    return { success: true, data: undefined };
  });
}

// ===== Supplementary Interview =====

/**
 * Create a supplementary interview to fill knowledge gaps
 */
export async function createSupplementaryInterview(sageId: number): Promise<
  ServerActionResult<{
    interview: SageInterview;
    userChat: UserChat;
  }>
> {
  return withAuth(async (user) => {
    try {
      // Check ownership and get sage info needed for interview plan
      const sage = await prisma.sage.findUnique({
        where: { id: sageId },
        select: {
          userId: true,
          name: true,
          domain: true,
          expertise: true,
        },
      });

      if (!sage) {
        return {
          success: false,
          message: "Sage not found",
          code: "not_found",
        };
      }

      if (sage.userId !== user.id) {
        return {
          success: false,
          message: "Unauthorized",
          code: "unauthorized",
        };
      }

      const locale = await getLocale();

      // Get pending knowledge gaps
      const pendingGaps = await prisma.sageKnowledgeGap.findMany({
        where: {
          sageId,
          resolvedAt: null,
        },
        select: {
          area: true,
          description: true,
          severity: true,
          impact: true,
        },
        orderBy: [{ severity: "desc" }, { createdAt: "asc" }],
      });

      if (pendingGaps.length === 0) {
        return {
          success: false,
          message: locale === "zh-CN" ? "没有待解决的知识空白" : "No pending knowledge gaps",
          code: "forbidden",
        };
      }

      // Convert to format expected by generateInterviewPlan
      const fullKnowledgeGaps = pendingGaps.map((gap) => ({
        area: gap.area,
        severity: gap.severity as SageKnowledgeGapSeverity,
        description: gap.description,
        impact: gap.impact,
        suggestedQuestions: [], // Will be generated by AI
      }));

      // Generate interview plan
      const interviewPlan = await generateInterviewPlan({
        sage: {
          name: sage.name,
          domain: sage.domain,
          expertise: sage.expertise as string[],
        },
        knowledgeGaps: fullKnowledgeGaps,
        locale,
      });

      // Create UserChat for interview
      const userChat = await createUserChat({
        userId: user.id,
        kind: "sageSession",
        title: `Interview: ${sage.name}`,
      });

      // Create SageInterview
      const interview = await prisma.sageInterview.create({
        data: {
          sageId,
          userChatId: userChat.id,
          extra: {
            startsAt: Date.now(),
            ongoing: true,
            interviewPlan,
          } as SageInterviewExtra,
        },
      });

      rootLogger.info(`Created supplementary interview ${interview.id} for sage ${sageId}`);

      return {
        success: true,
        data: { interview, userChat },
      };
    } catch (error) {
      rootLogger.error(`Failed to create supplementary interview: ${error}`);
      return {
        success: false,
        message: "Failed to create supplementary interview",
        code: "internal_server_error",
      };
    }
  });
}

// ===== Source Processing =====

/**
 * Process all pending sources for a sage
 */
export async function processSageSources(sageId: number): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    // Check ownership and get token for revalidation
    const sage = await prisma.sage.findUnique({
      where: { id: sageId },
      select: {
        userId: true,
        token: true,
      },
    });

    if (!sage) {
      return {
        success: false,
        message: "Sage not found",
        code: "not_found",
      };
    }

    if (sage.userId !== user.id) {
      return {
        success: false,
        message: "Not authorized",
        code: "forbidden",
      };
    }

    // Trigger background processing of sources only
    waitUntil(processSourcesOnly(sageId));

    revalidatePath(`/sage/${sage.token}`);

    return { success: true, data: undefined };
  });
}

/**
 * Extract knowledge and build memory document from completed sources
 */
export async function extractSageKnowledge(sageId: number): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    // Check ownership and get token for revalidation
    const sage = await prisma.sage.findUnique({
      where: { id: sageId },
      select: {
        userId: true,
        token: true,
      },
    });

    if (!sage) {
      return {
        success: false,
        message: "Sage not found",
        code: "not_found",
      };
    }

    if (sage.userId !== user.id) {
      return {
        success: false,
        message: "Not authorized",
        code: "forbidden",
      };
    }

    const locale = await getLocale();

    // Trigger background knowledge extraction
    waitUntil(extractKnowledgeOnly({ sageId, locale }));

    revalidatePath(`/sage/${sage.token}`);

    return { success: true, data: undefined };
  });
}

/**
 * Update sage avatar
 */
export async function updateSageAvatar(
  sageId: number,
  avatarUrl: string,
): Promise<ServerActionResult<void>> {
  return withAuth(async (user) => {
    // Check ownership and get token for revalidation
    const sage = await prisma.sage.findUnique({
      where: { id: sageId },
      select: {
        userId: true,
        token: true,
      },
    });

    if (!sage) {
      return {
        success: false,
        message: "Sage not found",
        code: "not_found",
      };
    }

    if (sage.userId !== user.id) {
      return {
        success: false,
        message: "Not authorized",
        code: "forbidden",
      };
    }

    await prisma.sage.update({
      where: { id: sageId },
      data: {
        avatar: { url: avatarUrl },
      },
    });

    revalidatePath(`/sage/${sage.token}`);
    revalidatePath(`/sage/profile/${sage.token}`);

    return { success: true, data: undefined };
  });
}
