export const UNIVERSAL_CHAT_SYNC_VISIBLE_POLL_INTERVAL_MS = 8000;
export const UNIVERSAL_SUB_AGENT_RUNTIME_VISIBLE_POLL_INTERVAL_MS = 10000;
export const UNIVERSAL_TASK_DETAIL_VISIBLE_POLL_INTERVAL_MS = 8000;

export const UNIVERSAL_HIDDEN_POLL_INTERVAL_MS = 30000;
export const UNIVERSAL_BUSY_RETRY_INTERVAL_MS = 3000;

export const UNIVERSAL_REPORT_RETRY_DELAYS_MS = [3000, 6000, 10000] as const;
